### ISSUE TITLE
Apply on Kobuki flatform

### ISSUE THREAD

**Issue by Seokjinoh** [googlecartographer/cartographer_turtlebot#30] opened 2016-11-10 02:14 UTC
Hello, I'm the user of Kobuki flatform and trying to use this package to my robot. As a beginner, I couldn't find all the things I need to modify from this package. I have a Hokuyo LRF (UTM-30LX). Could you answer or give me the hint? Thank you

**Comment by SirVer** [comment] 2016-11-10 09:53
Is this a turtlebot? If so, you can get started quickly using https://github.com/googlecartographer/cartographer_turtlebot. 

Otherwise, you can find documentation of how to run our stuff with demos [here](https://google-cartographer-ros.readthedocs.io/en/latest/). The `backpack 2d` demo is probably closest to what you have, though you might need to disable the IMU. 

Closing, since this is not a bug report. If you have specific questions about using Cartographer, please post on the [mailing list](https://groups.google.com/forum/#!forum/google-cartographer). If you have questions about ROS, I suggest http://answers.ros.org/questions/.

**Closed by SirVer** 2016-11-10 09:53 UTC
